### ISSUE TITLE
How to make use of event handler props like (plotly_click)? 

### ISSUE THREAD

**Issue by desmondblue** [plotly/angular-plotly.js#108]
Hi. I have been trying to integrate plotly_click event like

<plotly-plot [data]=graph.data [layout]=graph.layout (plotly_click)="trigger($event)"></plotly>

I can't get any response for the same:

TS Code:
trigger(event){
console.log(event)}

**Comment by desmondblue** [comment]
Do we need to include anything that I might be missing? I have imported the PlotlyModule. I went over your demo codes, I am unable to see why point_click is not being registered as an event more importantly when I use  point_click in the tag it comes like : 
<plotly-plot [data]=graph.data [layout]=graph.layout (plotly_click)="trigger($event)">
plotly is blue and _click normal text

**Comment by desmondblue** [comment]
Hi I tried specifying hovermode and click mode in ts code to no avail

**Comment by andrefarzat** [comment]
hello @desmondblue . As you described, it should be working. May I ask you the complete code for both HTML and TS ?

**Comment by desmondblue** [comment]
I am sorry I can't provide the code as its too wide and it will take too much time to understand the functioning. As per your quickstart guide I imported the Plotly modules correctly and did all the necessary steps still not working. Also I used the angular hover event and click event they are working fine. While for the click event ($event) is returning MouseEvent in hover ($event) is giving the dictionary of {points and etc.} . I tried all the predefined events doubleclick and everything and none of them are working

**Comment by andrefarzat** [comment]
@desmondblue it's hard to tell what is the issue without knowing how to reproduce the bug. May I ask you to create an example using the demo on this repository ? I am asking this because usually I create an example replicating the issue and presenting to the reporter to guarantee  it was solved. 

Here are screenshots of the demo with the `plotly_click` working: 

<img width="1750" alt="Screen Shot 2020-04-03 at 20 36 49" src="https://user-images.githubusercontent.com/649219/78412854-5a3e0600-75eb-11ea-9f48-c331a7e11604.png">
<img width="1750" alt="Screen Shot 2020-04-03 at 20 36 45" src="https://user-images.githubusercontent.com/649219/78412857-5ca06000-75eb-11ea-88dc-4f918dff7570.png">
<img width="1750" alt="Screen Shot 2020-04-03 at 20 36 32" src="https://user-images.githubusercontent.com/649219/78412863-5f02ba00-75eb-11ea-9477-e8bd7997d9de.png">

**Comment by BrunoAntonioA** [comment]
Hello! I've the same issue. I've a similar code of Andre, but it doesn't work

**Comment by kajal221954** [comment]
plotly_click also not working on my case also
